#
# Copyright 2024 Avnet Silica
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += sm2s_imx8mm.o boardinfo.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += lpddr4_mt53b512m32d2np_2gib_2chn_2cs_dv1_timing.o
obj-y += lpddr4_nt6an512t32avj2i_2gib_2chn_1cs_timing.o
endif
